### ISSUE TITLE
cookies doesn't have "ezproxy"

### ISSUE THREAD

**Issue by JaniceXiong** [hfthair/emerald_crawler#1]
I login and find cookies in Application, but **the key "ezproxy" doesn't exist** there, so I only change other value in cookies.py. But the error "need login!!" occured when I try to run the download.py script,
![image](https://user-images.githubusercontent.com/43976565/126108059-bc362921-4eb7-455e-8cca-24dbec4a57b7.png)
![image](https://user-images.githubusercontent.com/43976565/126108081-48feca1f-9bd5-417e-a075-d874c9ea3d49.png)
Could you tell me how to solve it?

**Comment by JaniceXiong** [comment]
And when I use the "skip open access" command, the error "No such file or directory: 'availability.json'" occurs.

**Comment by JaniceXiong** [comment]
Need to login here?
![image](https://user-images.githubusercontent.com/43976565/126109739-07ba47ed-c6b6-43c4-9cb0-7ce17c31c7fd.png)

**Comment by hfthair** [comment]
Thanks for your feedback! 
1. Please make sure you have access to the full paper after login. It is ok if one or two keys are different (or missing), as long as cookies.py has exact same key/value pairs from your browser, you should be able to start downloading. 
2. Do not use "skip open access" command, I have removed that. If you wish to download open access portion of emerald only, please use `python download.py --save_dir .`
