### ISSUE TITLE
Question about the implementation of BART-Facet 

### ISSUE THREAD

**Issue by JaniceXiong** [hfthair/emerald_crawler#4]
I am confused about "indicator" amd "section tags" described in the implementation of BART-Facet. 
![image](https://user-images.githubusercontent.com/43976565/128353626-e38b886a-38f7-44f8-88af-e1572ad37799.png)
Could you give an example like if I want to predict the **Purpose** of the article, how to change the src (full or I+C) and tgt?
![image](https://user-images.githubusercontent.com/43976565/128354679-6eb59942-548e-4675-b170-0cc1a5ceef9b.png)

We train the model for purpose, method, findings, value separately, or just train a model? If only a model, how can I tell the model which facet to generate?

**Comment by memray** [comment]
Hey @JaniceXiong ,

We append a special token (e.g. __PURPOSE__) at the beginning of the source text to indicate the facet of summary to generate.
And we train a single model to generate all facets.

Best,
Rui

**Comment by JaniceXiong** [comment]
Thanks a lot @memray
But how about the **"section tags" at the begining of each training input**? I read the paper "Tldr: Extreme summarization of scientific documents" which describes CATTS. CATTS means a scaffold task to predict titles indicated by control codes. How to use CATTS in your model?
I want to build the model described in your papar, and these details seem important :)

**Comment by memray** [comment]
Oh I only mean that we use the control code to indicate the facet to output, as illustrated in the figure below. We didn't use the title generation as an auxiliary training task.
![facet_sum](https://user-images.githubusercontent.com/4197249/128655172-173e9925-b6cf-41d1-ad83-3fc44ced9cd5.png)

We are organizing our code for data processing and it will be available very soon. Also, our [slides](http://memray.me/uploads/acl2021-emerald-faceted-summarization-slides.pdf) might be useful for clarification.

Best,
Rui

**Comment by JaniceXiong** [comment]
Ok I got it! Thanks again for your work and reply !!! @memray

**Comment by JaniceXiong** [comment]
I have another question about **"Full"** in result tables.
![image](https://user-images.githubusercontent.com/43976565/128676942-509395b9-053f-49ba-aa60-8c99b04398c7.png)
 
BART-Faceted summarize a specific facet at a time, but BART-CAT generate a long summary by concatenating all facets. When comparing these two model, did you concatenate all the facets summarized by BART-Faceted?

**Comment by memray** [comment]
@JaniceXiong Yes, that's right.

**Comment by JaniceXiong** [comment]
@memray Thanks! By the way, do you have a plan to release the model code and pretrained model?
