### ISSUE TITLE
Code for Structural Alignment

### ISSUE THREAD

**Issue by billy322** [hfthair/emerald_crawler#7]
Hi, 
In the paper, there is a part to align different abstract facets with the sections in an article. Can I know which part of the code corresponds to this function? Thanks.

**Comment by memray** [comment]
hi @billy322, please check out this [notebook](https://github.com/hfthair/emerald_crawler/blob/main/notebooks/rouge_oracle_compare_rouge12lcs.ipynb) for alignment.
